<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE calendars [
<!ENTITY nbsp "&#160;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT calendars (calendar)>
<!ELEMENT calendar (year)*>
<!ELEMENT year (month)*>
<!ELEMENT month (week)*>
<!ELEMENT week (day)*>
<!-- * 'day' can have zero or more 'job' child elements --><!ELEMENT day (job)*>
<!ELEMENT job (#PCDATA)>
<!ATTLIST calendar id CDATA #REQUIRED>
<!ATTLIST year ordinal CDATA #REQUIRED>
<!ATTLIST month ordinal CDATA #REQUIRED>
<!ATTLIST month name CDATA #REQUIRED>
<!ATTLIST week ordinal CDATA #REQUIRED>
<!ATTLIST day ordinal CDATA #REQUIRED>
<!ATTLIST day name CDATA #REQUIRED>
<!ATTLIST day date CDATA #REQUIRED>
<!ATTLIST job number CDATA #REQUIRED>
]>
<calendars>
  <calendar id="Custom Sign Center">
    <year ordinal="2022">
      <month ordinal="10" name="October">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date=""></day>
          <day ordinal="5" name="Thursday" date=""></day>
          <day ordinal="6" name="Friday" date=""></day>
          <day ordinal="7" name="Saturday" date="1"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="2"></day>
          <day ordinal="9" name="Monday" date="3"></day>
          <day ordinal="10" name="Tuesday" date="4"></day>
          <day ordinal="11" name="Wednesday" date="5"></day>
          <day ordinal="12" name="Thursday" date="6"></day>
          <day ordinal="13" name="Friday" date="7"></day>
          <day ordinal="14" name="Saturday" date="8"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="9"></day>
          <day ordinal="16" name="Monday" date="10"></day>
          <day ordinal="17" name="Tuesday" date="11"></day>
          <day ordinal="18" name="Wednesday" date="12"></day>
          <day ordinal="19" name="Thursday" date="13"></day>
          <day ordinal="20" name="Friday" date="14"></day>
          <day ordinal="21" name="Saturday" date="15"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="16"></day>
          <day ordinal="23" name="Monday" date="17"></day>
          <day ordinal="24" name="Tuesday" date="18"></day>
          <day ordinal="25" name="Wednesday" date="19"></day>
          <day ordinal="26" name="Thursday" date="20"></day>
          <day ordinal="27" name="Friday" date="21"></day>
          <day ordinal="28" name="Saturday" date="22"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="23"></day>
          <day ordinal="30" name="Monday" date="24"></day>
          <day ordinal="31" name="Tuesday" date="25"></day>
          <day ordinal="32" name="Wednesday" date="26"></day>
          <day ordinal="33" name="Thursday" date="27"></day>
          <day ordinal="34" name="Friday" date="28"></day>
          <day ordinal="35" name="Saturday" date="29"></day>
        </week>
        <week ordinal="6">
          <day ordinal="36" name="Sunday" date="30"></day>
          <day ordinal="37" name="Monday" date="31"></day>
          <day ordinal="38" name="Tuesday" date=""></day>
          <day ordinal="39" name="Wednesday" date=""></day>
          <day ordinal="40" name="Thursday" date=""></day>
          <day ordinal="41" name="Friday" date=""></day>
          <day ordinal="42" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="11" name="November">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date="1"></day>
          <day ordinal="4" name="Wednesday" date="2"></day>
          <day ordinal="5" name="Thursday" date="3"></day>
          <day ordinal="6" name="Friday" date="4"></day>
          <day ordinal="7" name="Saturday" date="5"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="6"></day>
          <day ordinal="9" name="Monday" date="7"></day>
          <day ordinal="10" name="Tuesday" date="8"></day>
          <day ordinal="11" name="Wednesday" date="9"></day>
          <day ordinal="12" name="Thursday" date="10"></day>
          <day ordinal="13" name="Friday" date="11"></day>
          <day ordinal="14" name="Saturday" date="12"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="13"></day>
          <day ordinal="16" name="Monday" date="14"></day>
          <day ordinal="17" name="Tuesday" date="15"></day>
          <day ordinal="18" name="Wednesday" date="16"></day>
          <day ordinal="19" name="Thursday" date="17"></day>
          <day ordinal="20" name="Friday" date="18"></day>
          <day ordinal="21" name="Saturday" date="19"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="20"></day>
          <day ordinal="23" name="Monday" date="21"></day>
          <day ordinal="24" name="Tuesday" date="22"></day>
          <day ordinal="25" name="Wednesday" date="23"></day>
          <day ordinal="26" name="Thursday" date="24"></day>
          <day ordinal="27" name="Friday" date="25"></day>
          <day ordinal="28" name="Saturday" date="26"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="27"></day>
          <day ordinal="30" name="Monday" date="28"></day>
          <day ordinal="31" name="Tuesday" date="29"><job number="120206">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120206"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120206*^*span#$# Nova Triad Partners llc Winston-Salem, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Address *^*span#$#*^*li#$#</job><job number="87773-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_87773-1"#$#87773-1*^*span#$# Wendy's 01849 Raleigh, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job><job number="113928-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_113928-1"#$#~~i class="ic-shield"#$#*^*i#$#113928-1*^*span#$# Wendy's Site 09174 Urbandale, IA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: U0900-IA-DIR-ENT-FACE-L*^*span#$#*^*li#$#</job></day>
          <day ordinal="32" name="Wednesday" date="30"><job number="119687-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119687-1"#$#~~i class="ic-ups"#$#*^*i#$#119687-1*^*span#$# Wendy's Site 04139 Onalaska, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: int. package *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: SHIPPED OUR PART ONLY = WAITING ON CREATIVE PALETTE FREIGHT COST TO DROP SHIP .... *^*span#$#*^*li#$#</job><job number="120186">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120186"#$#~~i class="ic-ups"#$#*^*i#$#120186*^*span#$# The Wasserstrom Company~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: TH-SC-BLOCKER-39*^*span#$#*^*li#$#</job><job number="120404">~~li class="lineEntry t9" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120404"#$#120404*^*span#$# The Villages of River Oak~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Alum Street blades*^*span#$#*^*li#$#</job></day>
          <day ordinal="33" name="Thursday" date=""></day>
          <day ordinal="34" name="Friday" date=""></day>
          <day ordinal="35" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="12" name="December">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date=""></day>
          <day ordinal="5" name="Thursday" date="1"><job number="117859">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117859"#$#117859*^*span#$# ComFab*^*li#$#</job><job number="117856">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117856"#$#117856*^*span#$# ComFab*^*li#$#</job><job number="117601-1">~~li class="lineEntry t10 due" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117601-1"#$#~~i class="ic-ups"#$#*^*i#$#117601-1*^*span#$# Wendy's 6665~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 2- silver towers &amp; 1- rhr *^*span#$#*^*li#$#</job><job number="120547">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120547"#$#~~i class="ic-ups"#$#*^*i#$#120547*^*span#$# Outdoor/Simed Health~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: ship to customer *^*span#$#*^*li#$#</job></day>
          <day ordinal="6" name="Friday" date="2"><job number="116212">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_116212"#$#~~i class="ic-p-inf"#$#*^*i#$#116212*^*span#$# Wendy's Site 04523 San Diego, CA~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: menus only *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 12-2-21 = spoke to josh to ship on 12-7*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: asked to ship 1-21-22 but confirm before closer to date ..... *^*span#$#*^*li#$#</job><job number="120265">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120265"#$#120265*^*span#$# Wendy's site 09893 Jacksonville, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package outdoor install*^*span#$#*^*li#$#</job><job number="120246-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120246-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120246-1*^*span#$# Wendy's Site 11470 Portsmouth - VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: canopy*^*span#$#*^*li#$#</job><job number="120459">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120459"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120459*^*span#$# Wendy's 01360 South Hill, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: canopy*^*span#$#*^*li#$#</job><job number="119273-1">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_119273-1"#$#119273-1*^*span#$# TH#1667 Cross Lanes, WV*^*li#$#</job></day>
          <day ordinal="7" name="Saturday" date="3"><job number="119173">~~li class="lineEntry t4" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119173"#$#~~i class="ic-p-inf"#$#*^*i#$#119173*^*span#$# ROMANELLI &amp; HUGHES~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Post &amp; Panel*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: OUPS NEEDED *^*span#$#*^*li#$#</job></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="4"><job number="120382">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120382"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120382*^*span#$# ClearHome S 92nd E Ave Tulsa, OK~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: ACM &amp; Alum signs*^*span#$#*^*li#$#</job><job number="120384">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120384"#$#120384*^*span#$# TH-911557 Batavia~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: channel letters *^*span#$#*^*li#$#</job><job number="120317">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120317"#$#120317*^*span#$# ClearHome Self Storage/Blue Island, IL~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Alum &amp; Vinyl*^*span#$#*^*li#$#</job><job number="119689">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119689"#$#119689*^*span#$# Wendy's Site 13616 Bremerton, WA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job></day>
          <day ordinal="9" name="Monday" date="5"><job number="118446">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_118446"#$#118446*^*span#$# Tim Hortons #915694~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: ST. CLAIR SHORES *^*span#$#*^*li#$#</job><job number="120332">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120332"#$#120332*^*span#$# Wendy's site 07733 Wayne, NJ~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Wendy's Package for sub install*^*span#$#*^*li#$#</job><job number="120282">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120282"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120282*^*span#$# Wendy's site 09554 Butler, NJ~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package *^*span#$#*^*li#$#</job><job number="118081-1">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_118081-1"#$#118081-1*^*span#$# Wendy's Site 07391 Sunrise, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: permits and install*^*span#$#*^*li#$#</job><job number="105538-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_105538-2"#$#~~i class="ic-ups"#$#*^*i#$#105538-2*^*span#$# Wendy's Site 01902 Virginia Beach - VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job></day>
          <day ordinal="10" name="Tuesday" date="6"></day>
          <day ordinal="11" name="Wednesday" date="7"><job number="119316">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119316"#$#~~i class="ic-p-inf"#$#*^*i#$#~~i class="ic-i-comp-inv"#$#*^*i#$#119316*^*span#$# TH920073 Jamestown, NY~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: PER BLAKE HAVE ARRIVE LAST WEEK OF OCTOBER TO HIS SUB *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Ship Canopy *^*span#$#*^*li#$#</job><job number="120264">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120264"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120264*^*span#$# Identity Services LLC WEN 10417 Chicago, IL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: NON-STANDARD 5'-2" X 9'-0" Double Faced *** 10SA LED Illuminated ***  Sign (sign only) BOTTOM REPLACEMENT SECTION OF WP100 *^*span#$#*^*li#$#</job><job number="120013">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120013"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120013*^*span#$# Wendy's site 11308 Stroudsburg, PA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 11-2-22 = PER KEVIN &amp; TERYL THIS MUST DELIVER FIRST WEEK OF DECEMBER AT LATEST .... *^*span#$#*^*li#$#</job><job number="99315-6">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_99315-6"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#99315-6*^*span#$# Wendy's Site 07680 Uhrichsville, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: canopy *^*span#$#*^*li#$#</job><job number="120524">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120524"#$#120524*^*span#$# Precision Signs WEN 11018 Albert Lea, MN~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: 1700 menu*^*span#$#*^*li#$#</job><job number="100986-6">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_100986-6"#$#100986-6*^*span#$# Wendy's Site #07622*^*li#$#</job></day>
          <day ordinal="12" name="Thursday" date="8"><job number="117855">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117855"#$#117855*^*span#$# ComFab*^*li#$#</job></day>
          <day ordinal="13" name="Friday" date="9"><job number="120263">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120263"#$#120263*^*span#$# Wendy's site 09669 Jacksonville, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package outdoor install*^*span#$#*^*li#$#</job><job number="120636">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120636"#$#120636*^*span#$# ClearHome Self Storage*^*li#$#</job><job number="120637">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120637"#$#120637*^*span#$# ClearHome Self Storage*^*li#$#</job></day>
          <day ordinal="14" name="Saturday" date="10"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="11"><job number="119687">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119687"#$#119687*^*span#$# Wendy's Site 04139 Onalaska, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: small package *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: note = this will not ship to sign effectz shop and will go to his sub ..... don to get me address *^*span#$#*^*li#$#</job></day>
          <day ordinal="16" name="Monday" date="12"><job number="119328">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_119328"#$#119328*^*span#$# COM FAB/RTA*^*li#$#</job></day>
          <day ordinal="17" name="Tuesday" date="13"><job number="120013-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120013-1"#$#120013-1*^*span#$# Wendy's site 11308 Stroudsburg, PA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: creative pallete *^*span#$#*^*li#$#</job><job number="120007-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120007-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120007-1*^*span#$# Wendy's Site 04983 E. Stroudsburg, PA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Creative pallet *^*span#$#*^*li#$#</job><job number="120282-1">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120282-1"#$#120282-1*^*span#$# Wendy's site 09554 Butler, NJ~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: install for120282*^*span#$#*^*li#$#</job><job number="120620">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false"#$#  	 ~~span id="job_120620"#$#120620*^*span#$# F &amp; W PROPERTIES*^*li#$#</job></day>
          <day ordinal="18" name="Wednesday" date="14"><job number="120332-1">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120332-1"#$#120332-1*^*span#$# Wendy's site 07733 Wayne, NJ~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: install for 120332*^*span#$#*^*li#$#</job><job number="120353">~~li class="lineEntry t8" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_120353"#$#120353*^*span#$# ClearHome Tulsa OK*^*li#$#</job><job number="119999">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119999"#$#119999*^*span#$# ClearHome Self Storage Oklahoma City~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package*^*span#$#*^*li#$#</job></day>
          <day ordinal="19" name="Thursday" date="15"><job number="109150-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_109150-1"#$#109150-1*^*span#$# WEN #00678 Oklahoma City, OK~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: retainer buy out *^*span#$#*^*li#$#</job></day>
          <day ordinal="20" name="Friday" date="16"><job number="120062">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120062"#$#120062*^*span#$# Wendy's site 09131 Jacksonville, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Small package with a 150WHR*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: SHIP TO OUTDOOR FOR INSTALL WEEK OF 11-28-22 *^*span#$#*^*li#$#</job><job number="119464">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119464"#$#119464*^*span#$# Wendy's Site 13414 Elverson, PA~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Full Package*^*span#$#*^*li#$#</job><job number="120632">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_120632"#$#120632*^*span#$# Wagenbrenner Professional Real Estate*^*li#$#</job><job number="120062-1">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120062-1"#$#120062-1*^*span#$# Wendy's site 09131 Jacksonville, FL*^*li#$#</job><job number="119166-1">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_119166-1"#$#119166-1*^*span#$# Wendy's Site 06596 Regina, SK*^*li#$#</job></day>
          <day ordinal="21" name="Saturday" date="17"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="18"><job number="91862-1">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_91862-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#91862-1*^*span#$# Wendy's site 00478 Virginia Beach, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: canopy *^*span#$#*^*li#$#</job></day>
          <day ordinal="23" name="Monday" date="19"><job number="120520">~~li class="lineEntry t9" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120520"#$#120520*^*span#$# Willow Glen~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Routed PVC Address Plaques x80*^*span#$#*^*li#$#</job><job number="109773-5">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_109773-5"#$#109773-5*^*span#$# Wendy's Site 09106 Jacksonville - FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Replacement face for 36" OLD STYLE OVAL cameo*^*span#$#*^*li#$#</job><job number="75022-1">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_75022-1"#$#75022-1*^*span#$# Wendy's site 05774 Lawrence, KS~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu*^*span#$#*^*li#$#</job><job number="111895-2">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_111895-2"#$#111895-2*^*span#$# Wendy's Site #05358 Conway, SC~~span class="admin-note"#$# [~~i style="color:#f00"#$#Ter*^*i#$#]: door plastic *^*span#$#*^*li#$#</job><job number="119559-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119559-2"#$#~~i class="ic-ups"#$#*^*i#$#119559-2*^*span#$# Wendy's Site 11200 Kansas City, MO~~span class="admin-note"#$# [~~i style="color:#f00"#$#Ter*^*i#$#]: dir face *^*span#$#*^*li#$#</job><job number="110530-4">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_110530-4"#$#~~i class="ic-ups"#$#*^*i#$#110530-4*^*span#$# Wendy's Site 09487 La Crosse, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#Ter*^*i#$#]: dir face *^*span#$#*^*li#$#</job></day>
          <day ordinal="24" name="Tuesday" date="20"><job number="120537">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120537"#$#120537*^*span#$# BVW Property Management~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Routed PVC*^*span#$#*^*li#$#</job><job number="120538">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120538"#$#120538*^*span#$# Scates Builders at Bethel Pointe LLC~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Routed PVC*^*span#$#*^*li#$#</job><job number="111941-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_111941-1"#$#~~i class="ic-ups"#$#*^*i#$#111941-1*^*span#$# Wendy's Site #02837 Bellefontaine, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="109342-5">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_109342-5"#$#109342-5*^*span#$# Wendy's Site #11195~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: 109342-5 NON-STANDARD SECOND GENERATION ROUND 48" *^*span#$#*^*li#$#</job><job number="120583">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120583"#$#120583*^*span#$# Wendy's site 09489 Sturtevant, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus and art pack *^*span#$#*^*li#$#</job><job number="120577">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120577"#$#~~i class="ic-ups"#$#*^*i#$#120577*^*span#$# Robert Miller~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job></day>
          <day ordinal="25" name="Wednesday" date="21"><job number="120596">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120596"#$#120596*^*span#$# Wendy's Site 05424 Carson City, NV~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Face*^*span#$#*^*li#$#</job><job number="120717">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120717"#$#120717*^*span#$# Realistar*^*li#$#</job></day>
          <day ordinal="26" name="Thursday" date="22"><job number="111182-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_111182-1"#$#~~i class="ic-ups"#$#*^*i#$#111182-1*^*span#$# Wendy's Site #06821 Olds, AB~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: rhr power supply*^*span#$#*^*li#$#</job><job number="120738">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120738"#$#120738*^*span#$# Custom Sign Center*^*li#$#</job></day>
          <day ordinal="27" name="Friday" date="23"><job number="117101">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117101"#$#117101*^*span#$# ClearHome Self Storage - Fort Walton~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package *^*span#$#*^*li#$#</job><job number="120253">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120253"#$#120253*^*span#$# Tim Hortons~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 1- directional to NAS QUICK SIGNS *^*span#$#*^*li#$#</job><job number="119321-1">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_119321-1"#$#119321-1*^*span#$# WEN #08452 Rockledge, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Pylon *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: ship to outdoor *^*span#$#*^*li#$#</job><job number="120429">~~li class="lineEntry t3" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_120429"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#120429*^*span#$# Savvy Auto Sales*^*li#$#</job><job number="111895-3">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_111895-3"#$#111895-3*^*span#$# Wendy's Site #05358 Conway, SC*^*li#$#</job><job number="117530-1">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_117530-1"#$#117530-1*^*span#$# Wendy's site 06463 North Bay, ON*^*li#$#</job><job number="120734">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120734"#$#120734*^*span#$# Custom Sign Center*^*li#$#</job></day>
          <day ordinal="28" name="Saturday" date="24"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="25"></day>
          <day ordinal="30" name="Monday" date="26"><job number="120746">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120746"#$#120746*^*span#$# Custom Sign Center*^*li#$#</job></day>