<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE calendars [
<!ENTITY nbsp "&#160;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT calendars (calendar)>
<!ELEMENT calendar (year)*>
<!ELEMENT year (month)*>
<!ELEMENT month (week)*>
<!ELEMENT week (day)*>
<!-- * 'day' can have zero or more 'job' child elements --><!ELEMENT day (job)*>
<!ELEMENT job (#PCDATA)>
<!ATTLIST calendar id CDATA #REQUIRED>
<!ATTLIST year ordinal CDATA #REQUIRED>
<!ATTLIST month ordinal CDATA #REQUIRED>
<!ATTLIST month name CDATA #REQUIRED>
<!ATTLIST week ordinal CDATA #REQUIRED>
<!ATTLIST day ordinal CDATA #REQUIRED>
<!ATTLIST day name CDATA #REQUIRED>
<!ATTLIST day date CDATA #REQUIRED>
<!ATTLIST job number CDATA #REQUIRED>
]>
<calendars>
  <calendar id="Custom Sign Center">
    <year ordinal="2022">     
      <month ordinal="10" name="October">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date=""></day>
          <day ordinal="5" name="Thursday" date=""></day>
          <day ordinal="6" name="Friday" date=""></day>
          <day ordinal="7" name="Saturday" date="1"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="2"></day>
          <day ordinal="9" name="Monday" date="3"></day>
          <day ordinal="10" name="Tuesday" date="4"></day>
          <day ordinal="11" name="Wednesday" date="5"></day>
          <day ordinal="12" name="Thursday" date="6"></day>
          <day ordinal="13" name="Friday" date="7"><job number="117530-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117530-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#117530-1*^*span#$# Wendy's site 06463 North Bay, ON~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job></day>
          <day ordinal="14" name="Saturday" date="8"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="9"></day>
          <day ordinal="16" name="Monday" date="10"></day>
          <day ordinal="17" name="Tuesday" date="11"></day>
          <day ordinal="18" name="Wednesday" date="12"><job number="120153">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120153"#$#~~i class="ic-ups"#$#*^*i#$#120153*^*span#$# Robert Miller~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job></day>
          <day ordinal="19" name="Thursday" date="13"></day>
          <day ordinal="20" name="Friday" date="14"></day>
          <day ordinal="21" name="Saturday" date="15"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="16"></day>
          <day ordinal="23" name="Monday" date="17"><job number="117903">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117903"#$#~~i class="ic-flag"#$#*^*i#$#117903*^*span#$# The Courtyards at River Bluff~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: CSC Install Street Signs *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: OUPS*^*span#$#*^*li#$#</job></day>
          <day ordinal="24" name="Tuesday" date="18"><job number="117086">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_117086"#$#117086*^*span#$# The Courtyards at Riverside Columbus, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: street signs ECT*^*span#$#*^*li#$#</job></day>
          <day ordinal="25" name="Wednesday" date="19"><job number="115891-1">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  	 ~~span id="job_115891-1"#$#~~i class="ic-flag"#$#*^*i#$#115891-1*^*span#$# The Courtyards at River Bluff~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: street signs*^*span#$#*^*li#$#</job></day>
          <day ordinal="26" name="Thursday" date="20"><job number="120186">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120186"#$#~~i class="ic-ups"#$#*^*i#$#120186*^*span#$# The Wasserstrom Company~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: TH-SC-BLOCKER-39*^*span#$#*^*li#$#</job><job number="102653-5">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_102653-5"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#102653-5*^*span#$# Wendy's site 11795 Norfolk, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120126">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120126"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120126*^*span#$# Wendy's site 00895 Norfolk, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120127">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120127"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120127*^*span#$# Wendy's site 09393 Garner, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="81276-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_81276-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#81276-1*^*span#$# Wendy's site 08217 Raleigh, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="86550-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_86550-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#86550-1*^*span#$# Wendy's site 01340 Raleigh, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="101250-3">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_101250-3"#$#~~i class="ic-ups"#$#*^*i#$#101250-3*^*span#$# Tyron Davis WEN 01772 Jacksonville, FL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="100352-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_100352-2"#$#~~i class="ic-ups"#$#*^*i#$#100352-2*^*span#$# Wendy's Site #04874 South Beloit, IL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120139">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120139"#$#~~i class="ic-ups"#$#*^*i#$#120139*^*span#$# Andrew Thomas~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu hardware *^*span#$#*^*li#$#</job><job number="120175">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120175"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120175*^*span#$# Wendy's site 06445 Maple, ON~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Que BRD*^*span#$#*^*li#$#</job><job number="120176">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120176"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120176*^*span#$# Wendy's site 6444 Ingersoll, ON~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Que *^*span#$#*^*li#$#</job><job number="120178">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120178"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120178*^*span#$# Wendy's Site 06446 Newcastle, ON~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: que*^*span#$#*^*li#$#</job></day>
          <day ordinal="27" name="Friday" date="21"><job number="118158">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_118158"#$#118158*^*span#$# The Courtyards on Hyatts Powell, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: street signs ect*^*span#$#*^*li#$#</job><job number="119687-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119687-1"#$#~~i class="ic-ups"#$#*^*i#$#119687-1*^*span#$# Wendy's Site 04139 Onalaska, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: int. package *^*span#$#*^*li#$#</job><job number="91447-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_91447-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#91447-1*^*span#$# Wendy's site 08129 Adairsville, GA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="111237-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_111237-1"#$#~~i class="ic-ups"#$#*^*i#$#111237-1*^*span#$# Wendy's site 04098 St. Peters, MO~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120335">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120335"#$#~~i class="ic-ups"#$#*^*i#$#120335*^*span#$# ClearHome Tulsa OK~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Banner*^*span#$#*^*li#$#</job><job number="120336">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120336"#$#~~i class="ic-ups"#$#*^*i#$#120336*^*span#$# ClearHome S 92nd E Ave Tulsa - OK~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Banner*^*span#$#*^*li#$#</job></day>
          <day ordinal="28" name="Saturday" date="22"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="23"></day>
          <day ordinal="30" name="Monday" date="24"><job number="109312-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_109312-2"#$#~~i class="ic-ups"#$#*^*i#$#109312-2*^*span#$# Wendy's Site #00118 Memphis, TN~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: 109312-2*^*span#$#*^*li#$#</job><job number="112836-3">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_112836-3"#$#~~i class="ic-ups"#$#*^*i#$#112836-3*^*span#$# Wendy's Site #12629 Ludlow, MA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="115673-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_115673-1"#$#~~i class="ic-ups"#$#*^*i#$#115673-1*^*span#$# Wendy's site 00131 Middletown, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120187">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120187"#$#120187*^*span#$# Nesco Resource~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: New Branding *^*span#$#*^*li#$#</job><job number="100138-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_100138-1"#$#~~i class="ic-ups"#$#*^*i#$#100138-1*^*span#$# WEN #00719 Franklin Park, IL~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job></day>
          <day ordinal="31" name="Tuesday" date="25"><job number="120243">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120243"#$#~~i class="ic-ups"#$#*^*i#$#120243*^*span#$# Sinkula Investments DBA Wendy s~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="119425-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119425-1"#$#~~i class="ic-ups"#$#*^*i#$#119425-1*^*span#$# Wendy's Site #00176 Springfield, OH~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Font Kit/Cabinet*^*span#$#*^*li#$#</job></day>
          <day ordinal="32" name="Wednesday" date="26"><job number="120324">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120324"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120324*^*span#$# ClearHome Self Storage - Volo~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: vinyl hours *^*span#$#*^*li#$#</job><job number="119993">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119993"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#119993*^*span#$# The Wasserstrom Company~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 3- TH BLOCKERS *^*span#$#*^*li#$#</job><job number="120054-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120054-1"#$#~~i class="ic-ups"#$#*^*i#$#120054-1*^*span#$# Wendy's site 05224 Fitchburg, WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Silver Merch, RHR and Creative Palette*^*span#$#*^*li#$#</job><job number="120246">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120246"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120246*^*span#$# Wendy's Site 11470 Portsmouth - VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120290">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120290"#$#120290*^*span#$# Kiddie Academy of Chester VA*^*li#$#</job></day>
          <day ordinal="33" name="Thursday" date="27"><job number="119756-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119756-1"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#119756-1*^*span#$# TH#9751~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 1- 24" HORTON'S REPLACEMENT FACE ONLY *^*span#$#*^*li#$#</job><job number="85932-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_85932-1"#$#~~i class="ic-ups"#$#*^*i#$#85932-1*^*span#$# Wendy's site 08989 Portsmouth, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="114338-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_114338-1"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#114338-1*^*span#$# Wendy's Site 01040 San Antonio, TX~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Menu Parts*^*span#$#*^*li#$#</job></day>
          <day ordinal="34" name="Friday" date="28"><job number="120042">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120042"#$#~~i class="ic-p-inf"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120042*^*span#$# Arthur Roberts~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Menu Parts*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: W/ MENU LOCKS ALSO ....*^*span#$#*^*li#$#</job><job number="117101-1">~~li class="lineEntry t8" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117101-1"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#117101-1*^*span#$# ClearHome Self Storage - Fort Walton*^*li#$#</job><job number="120160">~~li class="lineEntry t8" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_120160"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#120160*^*span#$# Lisa LaBanc Realty*^*li#$#</job><job number="120206">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120206"#$#~~i class="ic-ups"#$#*^*i#$#120206*^*span#$# Nova Triad Partners llc Winston-Salem, NC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Address *^*span#$#*^*li#$#</job></day>
          <day ordinal="35" name="Saturday" date="29"></day>
        </week>
        <week ordinal="6">
          <day ordinal="36" name="Sunday" date="30"></day>
          <day ordinal="37" name="Monday" date="31"><job number="117859">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117859"#$#117859*^*span#$# ComFab*^*li#$#</job><job number="92206-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_92206-2"#$#~~i class="ic-ups"#$#*^*i#$#92206-2*^*span#$# Wendy's site 00863 Chesapeake, VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="97889-3">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_97889-3"#$#~~i class="ic-ups"#$#*^*i#$#97889-3*^*span#$# Wendy's Site 01018 Virginia Beach - VA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120252">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120252"#$#120252*^*span#$# The Courtyards on Hyland Run*^*li#$#</job></day>
          <day ordinal="38" name="Tuesday" date=""></day>
          <day ordinal="39" name="Wednesday" date=""></day>
          <day ordinal="40" name="Thursday" date=""></day>
          <day ordinal="41" name="Friday" date=""></day>
          <day ordinal="42" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="11" name="November">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date="1"><job number="119918">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119918"#$#119918*^*span#$# Wendy's site 13494 Carthage, TX~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job><job number="120134">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120134"#$#120134*^*span#$# Wendy's site 08415 Round Rock, TX~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job><job number="118829">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_118829"#$#118829*^*span#$# Wendy's Site 06713 Parksville, BC~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job><job number="119052">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119052"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#119052*^*span#$# Wendy's Site 06167 Cold Lake, AB~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job><job number="120276">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_120276"#$#120276*^*span#$# COM FAB/RTA*^*li#$#</job><job number="117856">~~li class="lineEntry t9" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_117856"#$#117856*^*span#$# ComFab*^*li#$#</job></day>
          <day ordinal="4" name="Wednesday" date="2"><job number="120389">~~li class="lineEntry t8" title="Right-Click for Options"#$#  	 ~~span id="job_120389"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#120389*^*span#$# Outdoor/Second Harvest~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: RUSH ACM JOB MUST SHIP HERE*^*span#$#*^*li#$#</job><job number="120072">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120072"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120072*^*span#$# Wendy's site 06877 Okotoks, AB~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Silver Merch*^*span#$#*^*li#$#</job><job number="120071">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120071"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#~~i class="ic-ups"#$#*^*i#$#120071*^*span#$# Wendy's Site 06813 Calgary, AB~~span class="admin-note"#$# [~~i style="color:#f00"#$#jre*^*i#$#]: Silver Merch*^*span#$#*^*li#$#</job><job number="115078-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_115078-1"#$#~~i class="ic-ups"#$#*^*i#$#115078-1*^*span#$# Wendy's Site 02567 Crowley - LA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job><job number="120397">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120397"#$#~~i class="ic-ups"#$#*^*i#$#120397*^*span#$# Brian H. Kelemen &amp; Associates~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu parts *^*span#$#*^*li#$#</job></day>
          <day ordinal="5" name="Thursday" date="3"><job number="117601-1">~~li class="lineEntry t10 due" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117601-1"#$#~~i class="ic-ups"#$#*^*i#$#117601-1*^*span#$# Wendy's 6665~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 2- silver towers &amp; 1- rhr *^*span#$#*^*li#$#</job><job number="111654-3">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_111654-3"#$#111654-3*^*span#$# Wendy's Site #11971 N. Wales, PA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job></day>
          <day ordinal="6" name="Friday" date="4"><job number="117101">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117101"#$#117101*^*span#$# ClearHome Self Storage - Fort Walton~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package *^*span#$#*^*li#$#</job><job number="120147">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120147"#$#120147*^*span#$# Tim Hortons 11152 Lockport, NY~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: faces *^*span#$#*^*li#$#</job><job number="120271">~~li class="lineEntry t8" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120271"#$#~~i class="ic-i-comp-inv"#$#*^*i#$#120271*^*span#$# Abaco Corporation*^*li#$#</job><job number="104249-1">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_104249-1"#$#~~i class="ic-ups"#$#*^*i#$#104249-1*^*span#$# WEN #04891 Cordova - TN~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: PVC cameo *^*span#$#*^*li#$#</job><job number="119365">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119365"#$#119365*^*span#$# ClearHome Self Storage~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: package Outdoor install*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: MUST SHIP TO OUTDOOR IMAGES AT 8:00AM !!!! *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: LAKELAND, FL *^*span#$#*^*li#$#</job><job number="117556">~~li class="lineEntry t6" title="Right-Click for Options" style=""#$#  	 ~~span id="job_117556"#$#117556*^*span#$# Kiddie Academy of Collegeville~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: HDU AND WALL SIGN *^*span#$#*^*li#$#</job></day>
          <day ordinal="7" name="Saturday" date="5"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="6"></day>
          <day ordinal="9" name="Monday" date="7"><job number="119340-2">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119340-2"#$#~~i class="ic-ups"#$#*^*i#$#119340-2*^*span#$# Wendy's Site 05152 Madison - WI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: DIR Faces *^*span#$#*^*li#$#</job></day>
          <day ordinal="10" name="Tuesday" date="8"><job number="119631">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119631"#$#119631*^*span#$# Wendy's Site 01657 Burlington, WA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menu*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 9-29-22 = DAN B. WANTS TO ARRIVE ON 11-14-22 CHECK BEFORE SHIPPING *^*span#$#*^*li#$#</job><job number="120152">~~li class="lineEntry t10" title="Right-Click for Options" style=""#$#  	 ~~span id="job_120152"#$#~~i class="ic-ups"#$#*^*i#$#120152*^*span#$# Covenant Development - Wyoming, MI~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: Address pvc *^*span#$#*^*li#$#</job><job number="120257">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120257"#$#120257*^*span#$# The Courtyards at Riverside*^*li#$#</job><job number="120270">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120270"#$#120270*^*span#$# The Courtyards at River Bluff*^*li#$#</job></day>
          <day ordinal="11" name="Wednesday" date="9"><job number="119689">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119689"#$#119689*^*span#$# Wendy's Site 13616 Bremerton, WA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#*^*li#$#</job></day>
          <day ordinal="12" name="Thursday" date="10"><job number="119343">~~li class="lineEntry t8 due t21" title="Right-Click for Options" style=""#$#  	 ~~span id="job_119343"#$#119343*^*span#$# Wendy's Site 12965 Sylvester, GA~~span class="admin-note"#$# [~~i style="color:#f00"#$#sam*^*i#$#]: menus *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: MUST SHIP HERE AND NO LATER !!! / UPS'D ANCHORS ONLY *^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Tab*^*i#$#]: 9-16-22 = this item is for id assoc stock only now = ship asap straight to them now *^*span#$#*^*li#$#</job><job number="120408">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_120408"#$#120408*^*span#$# The Courtyards at Morse Circle*^*li#$#</job></day>