<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE calendars [
<!ENTITY nbsp "&#160;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT calendars (calendar)>
<!ELEMENT calendar (year)*>
<!ELEMENT year (month)*>
<!ELEMENT month (week)*>
<!ELEMENT week (day)*>
<!-- * 'day' can have zero or more 'job' child elements --><!ELEMENT day (job)*>
<!ELEMENT job (#PCDATA)>
<!ATTLIST calendar id CDATA #REQUIRED>
<!ATTLIST year ordinal CDATA #REQUIRED>
<!ATTLIST month ordinal CDATA #REQUIRED>
<!ATTLIST month name CDATA #REQUIRED>
<!ATTLIST week ordinal CDATA #REQUIRED>
<!ATTLIST day ordinal CDATA #REQUIRED>
<!ATTLIST day name CDATA #REQUIRED>
<!ATTLIST day date CDATA #REQUIRED>
<!ATTLIST job number CDATA #REQUIRED>
]>
<calendars>
  <calendar id="Outdoor Images">
    <year ordinal="2024">
      <month ordinal="1" name="January">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date="1"></day>
          <day ordinal="3" name="Tuesday" date="2"></day>
          <day ordinal="4" name="Wednesday" date="3"></day>
          <day ordinal="5" name="Thursday" date="4"></day>
          <day ordinal="6" name="Friday" date="5"></day>
          <day ordinal="7" name="Saturday" date="6"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="7"></day>
          <day ordinal="9" name="Monday" date="8"></day>
          <day ordinal="10" name="Tuesday" date="9"></day>
          <day ordinal="11" name="Wednesday" date="10"></day>
          <day ordinal="12" name="Thursday" date="11"></day>
          <day ordinal="13" name="Friday" date="12"></day>
          <day ordinal="14" name="Saturday" date="13"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="14"></day>
          <day ordinal="16" name="Monday" date="15"></day>
          <day ordinal="17" name="Tuesday" date="16"></day>
          <day ordinal="18" name="Wednesday" date="17"></day>
          <day ordinal="19" name="Thursday" date="18"></day>
          <day ordinal="20" name="Friday" date="19"></day>
          <day ordinal="21" name="Saturday" date="20"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="21"></day>
          <day ordinal="23" name="Monday" date="22"></day>
          <day ordinal="24" name="Tuesday" date="23"></day>
          <day ordinal="25" name="Wednesday" date="24"></day>
          <day ordinal="26" name="Thursday" date="25"></day>
          <day ordinal="27" name="Friday" date="26"></day>
          <day ordinal="28" name="Saturday" date="27"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="28"></day>
          <day ordinal="30" name="Monday" date="29"></day>
          <day ordinal="31" name="Tuesday" date="30"></day>
          <day ordinal="32" name="Wednesday" date="31"></day>
          <day ordinal="33" name="Thursday" date=""></day>
          <day ordinal="34" name="Friday" date=""></day>
          <day ordinal="35" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="2" name="February">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date=""></day>
          <day ordinal="5" name="Thursday" date="1"></day>
          <day ordinal="6" name="Friday" date="2"></day>
          <day ordinal="7" name="Saturday" date="3"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="4"></day>
          <day ordinal="9" name="Monday" date="5"></day>
          <day ordinal="10" name="Tuesday" date="6"></day>
          <day ordinal="11" name="Wednesday" date="7"></day>
          <day ordinal="12" name="Thursday" date="8"></day>
          <day ordinal="13" name="Friday" date="9"></day>
          <day ordinal="14" name="Saturday" date="10"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="11"></day>
          <day ordinal="16" name="Monday" date="12"></day>
          <day ordinal="17" name="Tuesday" date="13"></day>
          <day ordinal="18" name="Wednesday" date="14"></day>
          <day ordinal="19" name="Thursday" date="15"></day>
          <day ordinal="20" name="Friday" date="16"></day>
          <day ordinal="21" name="Saturday" date="17"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="18"></day>
          <day ordinal="23" name="Monday" date="19"></day>
          <day ordinal="24" name="Tuesday" date="20"></day>
          <day ordinal="25" name="Wednesday" date="21"></day>
          <day ordinal="26" name="Thursday" date="22"></day>
          <day ordinal="27" name="Friday" date="23"></day>
          <day ordinal="28" name="Saturday" date="24"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="25"></day>
          <day ordinal="30" name="Monday" date="26"></day>
          <day ordinal="31" name="Tuesday" date="27"></day>
          <day ordinal="32" name="Wednesday" date="28"></day>
          <day ordinal="33" name="Thursday" date="29"></day>
          <day ordinal="34" name="Friday" date=""></day>
          <day ordinal="35" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="3" name="March">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date=""></day>
          <day ordinal="5" name="Thursday" date=""></day>
          <day ordinal="6" name="Friday" date="1"></day>
          <day ordinal="7" name="Saturday" date="2"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="3"></day>
          <day ordinal="9" name="Monday" date="4"></day>
          <day ordinal="10" name="Tuesday" date="5"></day>
          <day ordinal="11" name="Wednesday" date="6"></day>
          <day ordinal="12" name="Thursday" date="7"></day>
          <day ordinal="13" name="Friday" date="8"></day>
          <day ordinal="14" name="Saturday" date="9"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="10"></day>
          <day ordinal="16" name="Monday" date="11"></day>
          <day ordinal="17" name="Tuesday" date="12"><job number="2903-3">~~li class="lineEntry t1" title="Right-Click for Options" style=""#$#  	 ~~span id="job_2903-3"#$#~~i class="ic-i-comp-alt"#$#*^*i#$#2903-3*^*span#$# Allen Industries (OH) / Checkers #6312~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Ocala - Post new permit with extended expiration date.*^*span#$#*^*li#$#</job></day>
          <day ordinal="18" name="Wednesday" date="13"></day>
          <day ordinal="19" name="Thursday" date="14"></day>
          <day ordinal="20" name="Friday" date="15"></day>
          <day ordinal="21" name="Saturday" date="16"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="17"></day>
          <day ordinal="23" name="Monday" date="18"></day>
          <day ordinal="24" name="Tuesday" date="19"></day>
          <day ordinal="25" name="Wednesday" date="20"></day>
          <day ordinal="26" name="Thursday" date="21"></day>
          <day ordinal="27" name="Friday" date="22"></day>
          <day ordinal="28" name="Saturday" date="23"><job number="2571-5">~~li class="lineEntry t5" title="Right-Click for Options" style=""#$#  	 ~~span id="job_2571-5"#$#2571-5*^*span#$# Custom Sign Center / Wendy's #07631~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Permit Extension Fees*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: MIami*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Still need an electrician to pull elect. permits for both D/T window canopies. *^*span#$#*^*li#$#</job></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="24"></day>
          <day ordinal="30" name="Monday" date="25"></day>
          <day ordinal="31" name="Tuesday" date="26"><job number="99365-5">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_99365-5"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#99365-5*^*span#$# Custom Sign Center, Inc~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Wendy's #00523 / Pt. Charlotte (NW Tamiami Trl) - PYLON: Deliver font kit, storage box &amp; finish LED retro/socket trays - BLDG: 240LF EVO, 6' &amp; 8" D/T window canopies - DRIVE-THRU (foundations by others): Main menu, Pivoting canopy &amp; Clearance pole - DIRECTIONAL SIGN: ???*^*span#$#*^*li#$#</job><job number="99365-4">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_99365-4"#$#99365-4*^*span#$# Custom Sign Center / Wendy's #00523~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Pt. Charlotte (NW Tamiami Trl) - INTERIOR: Menu (NGK Curved), RHR, Silver Queues (Qty. 2), Full AP &amp; WF package. *^*span#$#*^*li#$#</job></day>
          <day ordinal="32" name="Wednesday" date="27"><job number="admin-note">~~li class="lineEntry t2" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Mark Monument Location for Locate - Tesla - Kissimmee*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry t2" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: 123464 Vixxo / Rent-A-Center / Kissimmee &amp; Orlando - Survey 2 locations*^*span#$#*^*li#$#</job><job number="copyof99365-5 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof99365-5 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#99365-5 [CONT.] *^*span#$# Custom Sign Center, Inc~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Wendy's #00523 / Pt. Charlotte (NW Tamiami Trl) - PYLON: Deliver font kit, storage box &amp; finish LED retro/socket trays - BLDG: 240LF EVO, 6' &amp; 8" D/T window canopies - DRIVE-THRU (foundations by others): Main menu, Pivoting canopy &amp; Clearance pole - DIRECTIONAL SIGN: ???*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry t3" title="Right Click for Options"#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Ft. Myers (Palm Beach Blvd) - Estero - Bonita Springs - Metal*^*span#$#*^*li#$#</job></day>
          <day ordinal="33" name="Thursday" date="28"><job number="copyof99365-5 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof99365-5 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#99365-5 [CONT.] *^*span#$# Custom Sign Center, Inc~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Wendy's #00523 / Pt. Charlotte (NW Tamiami Trl) - PYLON: Deliver font kit, storage box &amp; finish LED retro/socket trays - BLDG: 240LF EVO, 6' &amp; 8" D/T window canopies - DRIVE-THRU (foundations by others): Main menu, Pivoting canopy &amp; Clearance pole - DIRECTIONAL SIGN: ???*^*span#$#*^*li#$#</job></day>
          <day ordinal="34" name="Friday" date="29"><job number="admin-note">~~li class="lineEntry t2" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: 123884-1 McKee Const. / VA Clinic / Ocala - 9 ea. (9"x9") interoir ADA signs.*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry t2" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Happy Dave's Survey - Summerfield - CALL JUDY UPON ARRIVAL. *^*span#$#*^*li#$#</job><job number="copyof99365-5 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof99365-5 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#99365-5 [CONT.] *^*span#$# Custom Sign Center, Inc~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Wendy's #00523 / Pt. Charlotte (NW Tamiami Trl) - PYLON: Deliver font kit, storage box &amp; finish LED retro/socket trays - BLDG: 240LF EVO, 6' &amp; 8" D/T window canopies - DRIVE-THRU (foundations by others): Main menu, Pivoting canopy &amp; Clearance pole - DIRECTIONAL SIGN: ???*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry t5" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: 123301 CSC / Wendy's #10557 / Hollywood - PERMIT TARGET DATE*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry t5" title="Right Click for Options" style=""#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#Wel*^*i#$#]: 123361 Jones / Tire Outlet / Ocala - PERMIT IN-HAND TARGET DATE.*^*span#$#*^*li#$#</job></day>
          <day ordinal="35" name="Saturday" date="30"><job number="112688-1">~~li class="lineEntry t5" title="Right-Click for Options"#$#  	 ~~span id="job_112688-1"#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#112688-1*^*span#$# CSC / Wendy's #12398~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Naples*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: (Main D/T menu and directional sign(s) - Expose footers for engineer - Add additional foundation(s) as per engineer instructions.*^*span#$#*^*li#$#</job></day>
        </week>
        <week ordinal="6">
          <day ordinal="36" name="Sunday" date="31"></day>
          <day ordinal="37" name="Monday" date=""></day>
          <day ordinal="38" name="Tuesday" date=""></day>
          <day ordinal="39" name="Wednesday" date=""></day>
          <day ordinal="40" name="Thursday" date=""></day>
          <day ordinal="41" name="Friday" date=""></day>
          <day ordinal="42" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="4" name="April">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date="1"><job number="123445-1">~~li class="lineEntry t2" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123445-1"#$#123445-1*^*span#$# Walton Signage / H&amp;R Block #9887~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Melbourne Sq/ Mall*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: ON SITE 8:30AM - R&amp;R Interior Channel Logo face - NEED EXTENSION LADDER.*^*span#$#*^*li#$#</job><job number=" 123031-1">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span id="job_ 123031-1"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$# 123031-1*^*span#$# Principle / Tesla~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Kissimme - NEED EXCAVATOR &amp; DUMP TRUCK*^*span#$#*^*li#$#</job></day>
          <day ordinal="3" name="Tuesday" date="2"><job number="copyof 123031-1">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span class="copyof 123031-1"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$# 123031-1 [CONT.] *^*span#$# Principle / Tesla~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Kissimme - NEED EXCAVATOR &amp; DUMP TRUCK*^*span#$#*^*li#$#</job><job number="123460">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false" style=""#$#  	 ~~span id="job_123460"#$#~~i class="ic-flag"#$#*^*i#$#123460*^*span#$# Walton Signage / Block Advisors #8603*^*li#$#</job></day>
          <day ordinal="4" name="Wednesday" date="3"><job number="copyof 123031-1 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof 123031-1 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$# 123031-1 [CONT.] *^*span#$# Principle / Tesla~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Kissimme - NEED EXCAVATOR &amp; DUMP TRUCK*^*span#$#*^*li#$#</job><job number="123434-1">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123434-1"#$#~~i class="ic-flag"#$#*^*i#$#123434-1*^*span#$# McKee-Thomas Const./VA Clinic Ocala~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Install 15 Ea. 9"x9" interior ADA office signs &amp; inserts. *^*span#$#*^*li#$#</job></day>
          <day ordinal="5" name="Thursday" date="4"><job number="24336">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span id="job_24336"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#24336*^*span#$# Allen Ind. / Rooms to Go~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Clermont*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: NEED EXCAVATOR AND DUMP TRUCK*^*span#$#*^*li#$#</job></day>
          <day ordinal="6" name="Friday" date="5"><job number="copyof24336">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span class="copyof24336"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#24336 [CONT.] *^*span#$# Allen Ind. / Rooms to Go~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Clermont*^*span#$#*^*li#$#</job></day>
          <day ordinal="7" name="Saturday" date="6"></day>
        </week>
        <week ordinal="2">
          <day ordinal="8" name="Sunday" date="7"><job number="admin-note">~~li class="lineEntry unassigned" title="Right Click for Options"#$#~~span id="admin-note" contenteditable="false"#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Allen Industries / Home 2 Suites / Sanford - Need to survey Hi-Rise Pylon (Flex Faces)*^*span#$#*^*li#$#</job></day>
          <day ordinal="9" name="Monday" date="8"><job number="123254">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123254"#$#~~i class="ic-users"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123254*^*span#$# CSC / Wendy's #14066~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Williston*^*span#$#*^*li#$#</job></day>
          <day ordinal="10" name="Tuesday" date="9"><job number="copyof123254">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123254"#$#~~i class="ic-users"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123254 [CONT.] *^*span#$# CSC / Wendy's #14066~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Williston*^*span#$#*^*li#$#</job></day>
          <day ordinal="11" name="Wednesday" date="10"><job number="copyof123254 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123254 [CONT.]"#$#~~i class="ic-users"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123254 [CONT.] *^*span#$# CSC / Wendy's #14066~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Williston*^*span#$#*^*li#$#</job></day>
          <day ordinal="12" name="Thursday" date="11"><job number="copyof123254 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123254 [CONT.]"#$#~~i class="ic-users"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123254 [CONT.] *^*span#$# CSC / Wendy's #14066~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Williston*^*span#$#*^*li#$#</job></day>
          <day ordinal="13" name="Friday" date="12"><job number="copyof123254 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123254 [CONT.]"#$#~~i class="ic-users"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123254 [CONT.] *^*span#$# CSC / Wendy's #14066~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Williston*^*span#$#*^*li#$#</job><job number="123462">~~li class="lineEntry unassigned" title="Right-Click for Options"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_123462"#$#123462*^*span#$# Dimension Works~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Ocala - Pylon Reface - 4 faces*^*span#$#*^*li#$#</job></day>
          <day ordinal="14" name="Saturday" date="13"></day>
        </week>
        <week ordinal="3">
          <day ordinal="15" name="Sunday" date="14"></day>
          <day ordinal="16" name="Monday" date="15"><job number="123426">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123426"#$#~~i class="ic-p-insp-req"#$#*^*i#$#123426*^*span#$# CSC / Wendy's #00598~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Lakeland - Pylon RB LED retro &amp; Reface - 3 sets 36" flush CL, QIOR cabinet &amp; filler panel, QIOR FCO letters, 6' &amp; 8' D/T window canopies, 260LF Silver Trim, Clearance Pole &amp; Pivoting Canopy (foundations by others)*^*span#$#*^*li#$#</job></day>
          <day ordinal="17" name="Tuesday" date="16"><job number="copyof123426">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123426"#$#~~i class="ic-p-insp-req"#$#*^*i#$#123426 [CONT.] *^*span#$# CSC / Wendy's #00598~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Lakeland - Pylon RB LED retro &amp; Reface - 3 sets 36" flush CL, QIOR cabinet &amp; filler panel, QIOR FCO letters, 6' &amp; 8' D/T window canopies, 260LF Silver Trim, Clearance Pole &amp; Pivoting Canopy (foundations by others)*^*span#$#*^*li#$#</job><job number="123361">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123361"#$#~~i class="ic-flag"#$#*^*i#$#123361*^*span#$# Jones Sign / Tire Outlet~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Ocala *^*span#$#*^*li#$#</job></day>
          <day ordinal="18" name="Wednesday" date="17"><job number="copyof123426 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123426 [CONT.]"#$#~~i class="ic-p-insp-req"#$#*^*i#$#123426 [CONT.] *^*span#$# CSC / Wendy's #00598~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Lakeland - Pylon RB LED retro &amp; Reface - 3 sets 36" flush CL, QIOR cabinet &amp; filler panel, QIOR FCO letters, 6' &amp; 8' D/T window canopies, 260LF Silver Trim, Clearance Pole &amp; Pivoting Canopy (foundations by others)*^*span#$#*^*li#$#</job></day>
          <day ordinal="19" name="Thursday" date="18"><job number="copyof123426 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123426 [CONT.]"#$#~~i class="ic-p-insp-req"#$#*^*i#$#123426 [CONT.] *^*span#$# CSC / Wendy's #00598~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Lakeland - Pylon RB LED retro &amp; Reface - 3 sets 36" flush CL, QIOR cabinet &amp; filler panel, QIOR FCO letters, 6' &amp; 8' D/T window canopies, 260LF Silver Trim, Clearance Pole &amp; Pivoting Canopy (foundations by others)*^*span#$#*^*li#$#</job><job number="123454">~~li class="lineEntry unassigned" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123454"#$#~~i class="ic-flag"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#123454*^*span#$# Stratus / Papa John's~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Kissimmee*^*span#$#*^*li#$#</job></day>
          <day ordinal="20" name="Friday" date="19"><job number="123075">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123075"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#123075*^*span#$# Sign Pro / NEFCO~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando - 5'-6"x18'-9" backer w/ pre-mounted acrylic logo/letters.*^*span#$#*^*li#$#</job></day>
          <day ordinal="21" name="Saturday" date="20"></day>
        </week>
        <week ordinal="4">
          <day ordinal="22" name="Sunday" date="21"></day>
          <day ordinal="23" name="Monday" date="22"><job number="123068">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123068"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123068*^*span#$# CSC / Wendy's #13407~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando (Dowdy Rd)*^*span#$#*^*li#$#</job></day>
          <day ordinal="24" name="Tuesday" date="23"><job number="copyof123068">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123068"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123068 [CONT.] *^*span#$# CSC / Wendy's #13407~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando (Dowdy Rd)*^*span#$#*^*li#$#</job></day>
          <day ordinal="25" name="Wednesday" date="24"><job number="copyof123068 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123068 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123068 [CONT.] *^*span#$# CSC / Wendy's #13407~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando (Dowdy Rd)*^*span#$#*^*li#$#</job></day>
          <day ordinal="26" name="Thursday" date="25"><job number="copyof123068 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123068 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123068 [CONT.] *^*span#$# CSC / Wendy's #13407~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando (Dowdy Rd)*^*span#$#*^*li#$#</job></day>
          <day ordinal="27" name="Friday" date="26"><job number="copyof123068 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options" style=""#$#  	 ~~span class="copyof123068 [CONT.]"#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#123068 [CONT.] *^*span#$# CSC / Wendy's #13407~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Orlando (Dowdy Rd)*^*span#$#*^*li#$#</job></day>
          <day ordinal="28" name="Saturday" date="27"></day>
        </week>
        <week ordinal="5">
          <day ordinal="29" name="Sunday" date="28"></day>
          <day ordinal="30" name="Monday" date="29"><job number="122773-1">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span id="job_122773-1"#$#122773-1*^*span#$# CSC / Wendy's #07962~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Hialeah*^*span#$#*^*li#$#</job><job number="admin-note">~~li class="lineEntry unassigned" title="Right Click for Options"#$#~~span id="admin-note" contenteditable="false"#$#~~i class="ic-flag"#$#*^*i#$#~~i class="ic-p-appr"#$#*^*i#$#~~i class="ic-p-insp-req"#$#*^*i#$#~~i class="ic-users"#$#*^*i#$#&gt;*^*span#$#~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: 123302-2 Allen Ind. / Biggby Coffee / Ocala - RW CL (3 line stacked at 2'-8"x7'-3"), 2 each. 2'-6"x9'-0" vinyl appliques for BLANK faces. *^*span#$#*^*li#$#</job><job number="123302-2">~~li class="lineEntry unassigned" title="Right-Click for Options" contenteditable="false"#$#  ~~i class="ic-flag"#$# *^*i#$#	 ~~span id="job_123302-2"#$#123302-2*^*span#$# Allen Industries / Biggby Coffee #1021*^*li#$#</job></day>
          <day ordinal="31" name="Tuesday" date="30"><job number="copyof122773-1">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span class="copyof122773-1"#$#122773-1 [CONT.] *^*span#$# CSC / Wendy's #07962~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Hialeah*^*span#$#*^*li#$#</job><job number="123452">~~li class="lineEntry" title="Right-Click for Options" style=""#$#  	 ~~span id="job_123452"#$#~~i class="ic-p-appr"#$#*^*i#$#123452*^*span#$# Vista Clinical~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Ocala - Wall Cabinet Re-Face*^*span#$#*^*li#$#</job></day>
          <day ordinal="32" name="Wednesday" date=""></day>
          <day ordinal="33" name="Thursday" date=""></day>
          <day ordinal="34" name="Friday" date=""></day>
          <day ordinal="35" name="Saturday" date=""></day>
        </week>
      </month>
      <month ordinal="5" name="May">
        <week ordinal="1">
          <day ordinal="1" name="Sunday" date=""></day>
          <day ordinal="2" name="Monday" date=""></day>
          <day ordinal="3" name="Tuesday" date=""></day>
          <day ordinal="4" name="Wednesday" date="1"><job number="copyof122773-1 [CONT.]">~~li class="lineEntry t3" title="Right-Click for Options"#$#  	 ~~span class="copyof122773-1 [CONT.]"#$#122773-1 [CONT.] *^*span#$# CSC / Wendy's #07962~~span class="admin-note"#$# [~~i style="color:#f00"#$#tom*^*i#$#]: Hialeah*^*span#$#*^*li#$#</job></day>